name: inversion-demo
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.13
  - pytorch>=2.0.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - sqlite>=3.40.0
  - pyarrow>=10.0.0
  - jsonschema>=4.17.0
  - tqdm>=4.65.0
  - requests>=2.28.0
  - jupyter>=1.0.0
  - ipykernel>=6.20.0
  - pip>=23.0.0
  - pip:
    - openai>=1.0.0
    - vec2text>=0.0.13
    - chromadb>=0.4.0
    - redis>=4.5.0
    - sentence-transformers>=2.2.0
    - python-dotenv>=1.0.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - cyborgdb-lite>=0.10.1
    - psycopg2-binary>=2.9.0
    - ipywidgets